### ISSUE TITLE
Error writing to database 

### ISSUE THREAD

**Issue by chrispy08820** [frumbert/wp2moodle-moodle#10]
Hello,

Thanks a lot for creating this! I really appreciate it! Let me give a little back story. I am currently using Wordpress 3.9.2 and Moodle 2.7+ and I had previously used the SSO authentication method described on this website: http://blog.giuseppeurso.net/moodle-and-wordpress-single-sign-on-in-20-minutes-part-1/ however I have now disabled that in the authentication list. I installed everything just like you had specified on your Wordpress website. I even used the example you give in the URL below, but I am getting an error when clicking on the hyperlink created using the virtual private trainer shortcode on Wordpress. It will not even allow me to use the same credentials for both wordpress and moodle. I would like to set it up in such a way that a user pays for a course receives a hyperlink through wordpress and is able to enroll into the course automatically. Any help would be greatly appreciated!

http://wordpress.frumbert.org/examples/

**Comment by frumbert** [comment]
Since this problem was logged, I've added WooCommerce and MarketPress support to the wordpress-end plugin. Hopefully this sorted the issue.
