### ISSUE TITLE
WP4.1.1 and Moodle2.8.1

### ISSUE THREAD

**Issue by hallshouse** [frumbert/wp2moodle-moodle#14]
I'm getting to my Moodle site from WP, but the logout URL does not redirect back to my WP site.
Both sites are in the same domain.
Moodle is in a sub-domain of my WP site.
In Moodle I'm using the Essential Theme.

**Comment by frumbert** [comment]
Hmm, Moodle seems to not be redirecting. I've changed the code to use a 301 rather than 302 redirect to see if that helps. The logout hook seems to be running. Running moodle as a subdomain shouldn't matter, nor should the theme.
