### ISSUE TITLE
unenroll on moodle

### ISSUE THREAD

**Issue by leandrojcaetano** [frumbert/wp2moodle-moodle#20]
Hi, how to unenroll on moodle a user enrolled from plugin?

**Comment by frumbert** [comment]
If they are cohort enrolled, you don't (directly). This is as per moodle design - you have to manage the cohort members and remove them from there (though it will remove them from all courses that use that cohort as a membership provider). If they are directly enrolled or via a group, use the course user enrolment tool to remove the users.

wp2moodle doesn't have a way to unenrol the user. It may be something I could support using a different shortcode - I'll pen it into the idea book for now.

**Comment by leandrojcaetano** [comment]
Ah okay! They are precisely registered by cohorts through your plugin. Thank's for your help!
