### ISSUE TITLE
Page keeps loading when I open the post.

### ISSUE THREAD

**Issue by mikeross6233m** [frumbert/wp2moodle-moodle#21]
I really didn't understand how to do this.

I created a new post and clicked on the wp2moodle icon

and then I replace the code with this

[wp2moodle group='lms_group' target='_blank' authtext='Please log on']launch the course[/wp2moodle]

It should've shown me the post according to documentation, but the page keeps loading.

Please help me

**Comment by frumbert** [comment]
What version of Wordpress, Moodle, PHP, server, plugin build, and so on are you using? Are there any php errors according to your server logs on either the wordpress or moodle server?

**Comment by mikeross6233m** [comment]
I'm using wordpress 4.3.1, moodle 2.9.3, php 5.6.4 and I'm using latest plugin build from github

I dont know where to check the server logs but I think there are no server errors.

Do you think that it is a permission issue??

**Comment by mikeross6233m** [comment]
I checked the server logs and I got this

[Sun Nov 29 15:50:07.563115 2015] [:error] [pid 15351] [client 127.0.0.1:57276] core\\event\\user_loggedin Object\n(\n    [data:protected] => Array\n        (\n            [eventname] => \\core\\event\\user_loggedin\n            [component] => core\n            [action] => loggedin\n            [target] => user\n            [objecttable] => user\n            [objectid] => 2\n            [crud] => r\n            [edulevel] => 0\n            [contextid] => 1\n            [contextlevel] => 10\n            [contextinstanceid] => 0\n            [userid] => 2\n            [courseid] => 0\n            [relateduserid] => \n            [anonymous] => 0\n            [other] => Array\n                (\n                    [username] => admin\n                )\n\n            [timecreated] => 1448792407\n        )\n\n    [logextra:protected] => \n    [context:protected] => context_system Object\n        (\n            [_id:protected] => 1\n            [_contextlevel:protected] => 10\n            [_instanceid:protected] => 0\n            [_path:protected] => /1\n            [_depth:protected] => 1\n        )\n\n    [triggered:core\\event\\base:private] => 1\n    [dispatched:core\\event\\base:private] => \n    [restored:core\\event\\base:private] => \n    [recordsnapshots:core\\event\\base:private] => Array\n        (\n        )\n\n)\n, referer: http://localhost/moodle/?
[Sun Nov 29 15:50:07.563231 2015] [:error] [pid 15351] [client 127.0.0.1:57276] 2, referer: http://localhost/moodle/?
[Sun Nov 29 16:01:24.806120 2015] [:error] [pid 17934] [client 127.0.0.1:57480] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/html/wordpress2/wp-content/plugins/wp2moodle/wp2m.php on line 120, referer: http://localhost/wordpress2/?page_id=7

**Comment by scara** [comment]
`PHP Fatal error: Call to undefined function mcrypt_get_iv_size()` means that the server hosting your instance is missing the PHP _mcrypt_ library (package).

HTH,
Matteo

**Comment by frumbert** [comment]
Added a test in the (wordpress) plugin that notifies the user if mcrypt is not enabled.
