### ISSUE TITLE
Cannot process the script

### ISSUE THREAD

**Issue by Alehandro231** [frumbert/wp2moodle-moodle#23]
Good day!
Please help to understand.
During the transition from the WP website to the MOODLE site shows the message error processing script.
When moving from WP website on the Moodle site shows the error message of the script. All settings are done on WP and MOODLE.
On the MOODLE server rights to the directory wp2moodle done. 
The MOODLE server: Linux, Nginx, Php v 5.5.9, Php-fpm.

**Comment by frumbert** [comment]
Hmm, can you include the outputs of phpinfo()? do you happen to have the php error logs handy for the Moodle side?

**Comment by Alehandro231** [comment]
Yes, the log files are available.
Here is the information from the log files:
2016/07/24 18:22:08 [error] 857#0: *264354 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 64.137.249.120, server: site.su, request: "GET //phpMyAdmin-3.1.2.0-all-languages/scripts/setup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "91.226.85.187"

In the attachment file with phpinfo()
[PHPinfo().pdf](https://github.com/frumbert/wp2moodle-moodle/files/380839/PHPinfo.pdf)

**Comment by frumbert** [comment]
1. Do you have mcrypt installed on the server? (e.g. `sudo apt-get install php5-mcrypt && sudo php5enmod mcrypt`
2. The error in the log looks remarkably like http://serverfault.com/questions/734935/nginx-and-php-fpm-primary-script-unknown, which talks about document roots being the issue. (nginx isn't my strong suit)

**Comment by Alehandro231** [comment]
Nginx is configured in accordance with all laws and rules.
The problem was observed in the absence of. Fulfilled point #1 - everything works.
Thank You for your help.
