### ISSUE TITLE
Enrolment to course is not done.

### ISSUE THREAD

**Issue by vishalsood77** [frumbert/wp2moodle-moodle#25]
First of all thank you for such a easy and nice plugin for wp-> moodle integration. 

I have done all the steps and integrate the plugin with wp but I am facing one issue. Plugin able to registered a user to moodle but not able to enrol the user to the course. 
Being new to wp and php, I am not able to identify the problem. Could you help me to solve this problem.

Thanks, 
Vishal

**Comment by frumbert** [comment]
Tell me about your course and the shortcode you are using to open it. What are the enrolment providers that you have already set up for the course and how are they configured. Are you enroling the user into the course using a course, group or cohort enrolment type. Can you confirm that you are correctly using the idnumber fields and show the values you have in those.

**Comment by vishalsood77** [comment]
shortcode :  [wp2moodle course="eng_c_1"]launch the course[/wp2moodle]
enrolment provider - you mean enrolment method for course- I haven't set that value ?  Do i need to set this value.
Enrolling the user with course type. I am using the idnumber for course.

**Comment by frumbert** [comment]
Looks right so far. Your course should have its *Course ID number* set to `eng_c_1`, and have `manual` enrolment enabled as its enrolment method. If that's not working then try creating a group in the course (course admin > users > groups, then 'create group' button. Set its *Group ID number* to some value, then modify your shortcode to be [wp2moodle group='yourcode'] so that it enrols the user into that group instead. If that works then course enrolments might have a bug I haven't found yet. By the way, what version of Moodle are you using?

**Comment by vishalsood77** [comment]
Thank you for response, shortcode with Course ID number is not working, but group is working. I am using Moodle 3.1.1+ (Build: 20160804) and WordPress 4.5.3.

**Comment by frumbert** [comment]
Ok, I've had one other report including moodle 3.1 so I guess something in the course enrolment code has become problematic - I'll try to look into it.

**Comment by frumbert** [comment]
I'm not seeing the same problem under a brand new installation of moodle 3.1.1. are you not being enrolled at all into the course, or is the enrolment being done without launching the course? Is the server and moodle on the same site, or are they on different servers? Have you tried setting the Link Timeout to a higher value (e.g. 60) and ensured that the "Auto open course" setting is set to "yes".

**Comment by vishalsood77** [comment]
Not able to enrolled at all into the course. They are on sub domain and are on the same server.
Yes, I tried but no success.

**Comment by vishalsood77** [comment]
It is displaying the message 'You can not enrol yourself in this course.' when redirect to moodle course page using short code

**Comment by frumbert** [comment]
Can you show me (screenshots) these screens:
- (your course) > Course Administration > Users > Enrolment methods
- (your course) > Edit Settings
- Site Administration > Plugins > Enrolments > Manage enrol plugins
- Site Administration > Plugins > Authentication > Manage authentication
- Site Administration > Plugins > Authentication > Wordpress 2 Moodle (SSO)
- Site Administration > Security > Site Policies (anything that isn't at its default)

**Comment by vishalsood77** [comment]
Sorry for late reply !  Site Policies are default values.
Images link : [Images](https://drive.google.com/open?id=0B8PZdc1moCe4YkpQWDA0endoSkk)

**Comment by vishalsood77** [comment]
Any update ? 

thanks,
Vishal

**Comment by frumbert** [comment]
Sorry it's be a go-live week on another project - haven't had the time to work the problem yet

**Comment by vishalsood77** [comment]
Hi, 
Have you got a chance to see the issue ?

Thanks,
Vishal

**Comment by vishalsood77** [comment]
Sir, 
Any update ?

**Comment by frumbert** [comment]
Was unable to reproduce
