### ISSUE TITLE
Open a direct Link to a moodle activity

### ISSUE THREAD

**Issue by duennerd** [frumbert/wp2moodle-moodle#26]
Hello 

Great plugin. Exactly what I was looking for. 
Just one thing: Is it possible to open a link within the moodle site?
for example a specific activity? 

Thanks for your help. 

Greetings Daniel

**Comment by frumbert** [comment]
Yes, "sort of" is the best current answer to that. On your shortcode you can add the activity, something like this

    [wp2moodle course='abc123' activity='3']Open course[/wp2moodle]

BUT the limitation at the moment is that the activity must be visible, the section that it's in must be visible, and the index (3 in my example) is counted down from the first one. It might take a couple of goes to get right, but hopefully this should get you going.

Cheers,
Tim
