### ISSUE TITLE
Where i put the wp2moodle short code in wordpress.

### ISSUE THREAD

**Issue by gaurav12y** [frumbert/wp2moodle-moodle#28]
Where i put the wp2moodle short code in wordpress

**Comment by frumbert** [comment]
On a post or page that supports shortcodes. There's a button for it on your editor toolbar.
<img width="616" alt="screen shot 2017-08-13 at 7 42 52 am" src="https://user-images.githubusercontent.com/592257/29244430-0bc226f2-7ffb-11e7-8b9f-47ae38644a59.png">

**Comment by gaurav12y** [comment]
Thanks
