### ISSUE TITLE
wp2moodle woocomerce integration.

### ISSUE THREAD

**Issue by gaurav12y** [frumbert/wp2moodle-moodle#30]
Hi,

I have a multiple course on moodle and i want to sell from wordpress and read courses from moodle section,
 I have a question if user purchase a course from wordpress then how system get that particular course purchase buy user and how enrollment will work.
Thanks

**Comment by frumbert** [comment]
This plugin allows a special download file to be attached to a woocommerce product. The process is documented [here](http://wp2moodle.coursesuite.ninja/docs/wp2moodle/setting-up-2/setting-up/) as well as [here](https://github.com/frumbert/wp2moodle--wordpress-#e-commerce-integration). It basically works by representing courses in WooCommerce as virtual digital download products, which the user adds to using the normal cart / purchase mechanism you have set up in WooCommerce. Then, when the user tries to download the digital purchase, a hook in this plugin intercepts the download request and repackages it as a wp2moodle link and uses that to open the Moodle site (as if the user had clicked the shortcode link).

![image](https://user-images.githubusercontent.com/592257/29389849-15741c36-8330-11e7-91dc-bfe2230906f5.png)

Shortcodes are not used. You don't have to create pages and host links on them. The details of what course (or courses), group (or groups), cohort (or cohorts) and activity to open are details you put into a file that becomes the digital download product.
