### ISSUE TITLE
Wordpress Marketpress and Moodle integration

### ISSUE THREAD

**Issue by deonsa** [frumbert/wp2moodle-moodle#4]
Hi Tim,

I have a WP multisite with Marketpress installed.

What would be the best way to link the Marketpress products (courses) with the courses within Moodle with the wp2moodle plugin?

You mentioned cohorts before, but does this mean a cohort should be created for each course?

I'd greatly appreciate any advice you can give me.
Thanks
Deon

**Comment by frumbert** [comment]
Well, it's probably way too late, but there is now a solution for marketpress integration. The WPMU devs don't supply documentation, and were particularly unhelpful, so I did it my own way.
